### ISSUE TITLE
Re-license under Boost Software License (BSL)

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/span-lite#11]
Allow distribution of binaries using *span lite* without mentioning this project['s license].

- [Choose an open source license: Table](https://choosealicense.com/appendix/)
- [Boost Software License](https://www.boost.org/users/license.html)

@chris0e3 Would you agree to this change?

**Comment by chris0e3** [comment]
Yes.  It is absolutely fine by me.

**Comment by martinmoene** [comment]
Thanks! Done in [release 0.3.0](https://github.com/martinmoene/span-lite/releases/tag/v0.3.0).
