### ISSUE TITLE
Fix  span_CONFIG_CONTRACT_CHECK for contract-violation-terminates

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/span-lite#15]
`span_CONFIG_CONTRACT_CHECK` for contract-violation-terminates must honour condition; now it is unconditional (!)

**Comment by AndrewGaspar** [comment]
Can we get a new release at some point? This is a pretty annoying issue.

**Comment by martinmoene** [comment]
Will try the coming days...

Issue #14 and [nonstd-lite project 1](https://github.com/martinmoene/nonstd-lite-project/projects/1) almost have advanced _just enough_ to make release [milestone 0.4.0](https://github.com/martinmoene/span-lite/milestone/2) of _span lite_.

**Comment by martinmoene** [comment]
@AndrewGaspar Just Released [0.4.0](https://github.com/martinmoene/span-lite/releases/tag/v0.4.0).

**Comment by AndrewGaspar** [comment]
Thank you very much!

**Comment by AndrewGaspar** [comment]
Thank you very much!
