### ISSUE TITLE
Define missing macros span_HAVE_INLINE_NAMESPACE and span_CONFIG_CONTRACT_VIOLATION_THROWS_V

### ISSUE THREAD

**Issue by feroldi** [martinmoene/span-lite#24]
GCC (under -Werror=undef) whines about `span_HAVE_INLINE_NAMESPACE` and `span_CONFIG_CONTRACT_VIOLATION_THROWS_V` macros not being defined. The former one was actually missing a proper definition (C++11 and MSVC 14.0 have inline namespaces). The latter was a misuse: checking for an undefined macro's value.

[I made the changes myself](https://github.com/feroldi/span-lite/commit/acbb5441b3a57c881811a049e4bb180826c10334), but I'm not sure whether I should PR this.

**Comment by martinmoene** [comment]
Thanks @feroldi , I took care of it in the two commits mentioned above.

**Comment by feroldi** [comment]
Thanks!
