### ISSUE TITLE
Support nonstd::as_bytes using byte-lite when span_CPP17_OR_GREATER is false

### ISSUE THREAD

**Issue by ilyalesokhin** [martinmoene/span-lite#28]
Currently the nonstd::as_bytes and nonstd::as_writeable_bytes are not available without CPP17.
please consider supporting them with byte-lite byte implementation.

**Comment by chris-durand** [comment]
Implementing `std::byte` with a pre-C++17 compiler will result in undefined behaviour. Although it is simply defined as
```/// std::byte
  enum class byte : unsigned char {}; 
```
in most standard library implementations, it needs some special treatment by the compiler.

The usefulness of `std::byte` depends on a special exception to  [type aliasing rules](https://en.cppreference.com/w/cpp/language/reinterpret_cast#Type_aliasing) which is also added in C++17. It allows you to `reinterpret_cast` every `T*` to `std::byte*` and dereference the result without invoking undefined behaviour (just like for `char` and `const char`). This exception is actually hardcoded in the compiler implementation (e.g. the [commit from gcc](https://github.com/gcc-mirror/gcc/commit/85d41712eb8d58db22548b408f70b83ebe6691fc))

This line [here](https://github.com/martinmoene/span-lite/blob/master/include/nonstd/span.hpp#L1103)  in the implementation of `span` would be undefined behaviour with a custom `byte` and will produce invalid results with optimization turned on ([as this unittest from gcc](https://github.com/gcc-mirror/gcc/commit/85d41712eb8d58db22548b408f70b83ebe6691fc#diff-36caee472606f5a3f50e977222b37e61) shows).

**Comment by martinmoene** [comment]
Note to self:
```
#ifdef NONSTD_BYTE_LITE_HPP
# define span_HAVE_NONSTD_BYTE  1
#else
# define span_HAVE_NONSTD_BYTE  0
#endif

#if span_HAVE( BYTE )
...
#elif span_HAVE( NONSTD_BYTE )
... as_bytes(...)
... as_writeable_bytes(...)
#endif

#if span_FEATURE( BYTE_SPAN ) 
# if ( span_USES_STD_SPAN || span_HAVE( BYTE ) )
...
# elif span_HAVE( NONSTD_BYTE )
... byte_span( T & t ) ...
... byte_span( T const & t ) ...
# endif
#endif
```

**Comment by martinmoene** [comment]
@ilyalesokhin,Thanks for the suggestion. Implemented.
