### ISSUE TITLE
Review span in face of p1024, p1089, p1872 (Continued from #14)

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/span-lite#30]
References:
- Continued from #14
- [p1024 - Usability Enhancements for std::span](https://wg21.link/p1024),
  voted in, [2019-02 Kona ISO C++ Committee Trip Report](https://www.reddit.com/r/cpp/comments/au0c4x/201902_kona_iso_c_committee_trip_report_c20/)
- [p1085 - Should Span be Regular?](http://wg21.link/p1085): No comparison operators,
  voted in, [2018 Rapperswil ISO C++ Committee Trip Report](https://www.reddit.com/r/cpp/comments/8prqzm/2018_rapperswil_iso_c_committee_trip_report/)
- [p1089 - Sizes Should Only span Unsigned](https://wg21.link/p1089) - see #27
- [p1872 - span should have size_type, not index_type](http://wg21.link/p1872),
  voted in, [2019-11 Belfast ISO C++ Committee Trip Report](https://www.reddit.com/r/cpp/comments/dtuov8/201911_belfast_iso_c_committee_trip_report/)

Plan:
- [x] Rename `as_writeable_bytes()` to `as_writable_bytes()` (in r7, thanks to @nolange, see below)
- [x] Structured bindings support for fixed-size spans (only non-dynamically-sized spans) (p1024)
- [x] Change default of `span_FEATURE_COMPARISON` to `0` (p1085)
- [x] Change default of `span_CONFIG_SIZE_TYPE` to `std::size_t` (p1089)
- [x] Change default of `span_CONFIG_EXTENT_TYPE` to `std::size_t` (p1089)
- [x] Allow also for `Extent` to be unsigned with `dynamic_extent` `numeric_limits<index_type>::max()` or `static_cast<extent_t>(-1);` (p1089)
- [x] Rename index_type to size_type (p1872)

---

- Differentiate storage for dynamic, static extent: moved to #8 (duplicate #47)
- Use feature test macros: `defined(__cpp_deduction_guides)` etc.: moved to #48

**Comment by nolange** [comment]
some small change was apparently missed:
rename as_writeable_bytes -> as_writable_bytes
