### ISSUE TITLE
Add span_FEATURE_MAKE_SPAN

### ISSUE THREAD

**Issue by martinmoene** [martinmoene/span-lite#33]
Add configuration flag `span_FEATURE_MAKE_SPAN` to unconditionally control presence of `make_span()`

Plan:
- [x] Add span_FEATURE_MAKE_SPAN with priority above span_FEATURE_MAKE_SPAN_TO_STD
- [x] Add span_FEATURE_MAKE_SPAN to test/span-main.t.cpp
- [x] Document span_FEATURE_MAKE_SPAN, mentioning it precedes over span_FEATURE_MAKE_SPAN_TO_STD
- [x] In documentation of span_FEATURE_MAKE_SPAN_TO_STD, mention span_FEATURE_MAKE_SPAN takes precedence
- [x] Mention macro in table
- [x] Mention span_FEATURE_MAKE_SPAN in test/CMakeLists.txt
- [x] Mention span_FEATURE_MAKE_SPAN in test/t.bat, tg.bat, tc.bat

Originates from issue #32 .

Envisioned implementation:
```
#ifndef  span_FEATURE_MAKE_SPAN
#ifdef   span_FEATURE_MAKE_SPAN_TO_STD
# define span_FEATURE_MAKE_SPAN  span_IN_STD( span_FEATURE_MAKE_SPAN_TO_STD )
#else
# define span_FEATURE_MAKE_SPAN  0
#endif
#endif
```

**Comment by Flamefire** [comment]
Please do the same for all other `*_TO_STD` macros. Especially as e.g. the subspan function rely on this.
