### ISSUE TITLE
error in finding as_bytes when byte-lite is present

### ISSUE THREAD

**Issue by tsung-wei-huang** [martinmoene/span-lite#40]
I think you should do this in order to enable as_bytes function to your byte-lite library?
```cpp
#if span_HAVE( BYTE ) || span_HAVE( NONSTD_BYTE )
using span_lite::as_bytes;
using span_lite::as_writeable_bytes;
#endif
```
The original code doesn't have `span_HAVE( NONSTD_BYTE )` and that causes me error in using `as_bytes` even though `bite-lite` exists.

**Comment by martinmoene** [comment]
@tsung-wei-huang, sorry for reacting only now,

*span-lite* provides `as_bytes()`, `as_writable_bytes()` and `std::as_bytes()`, `std::as_writable_bytes()` via namespace `nonstd`.

So one can either use

```cpp
fun( span_lite::as_bytes( spn ) );  // explicitly specify namespace
```
or

```cpp
using namespace nonstd;
fun( as_bytes( spn ) );  // make everything from nonstd available
```
or

```cpp
fun( as_bytes( spn ) );  // ADL: argument-dependent lookup
```

**Comment by martinmoene** [comment]
Assuming this can be closed.
