### ISSUE TITLE
wrong release number in CMakeLists.txt

### ISSUE THREAD

**Issue by andijcr** [martinmoene/span-lite#43]
https://github.com/martinmoene/span-lite/blob/34118d2df7976f635c8fd35b5959f86cb52ba93c/CMakeLists.txt#L14

the release pointing to this tree is named 0.6.0, but in the CMakelists.txt it is still called 0.5.0

**Comment by martinmoene** [comment]
@flexferrum See / run `script/update-version.py` 

Projects need release etc. process descriptions...

**Comment by martinmoene** [comment]
Updated to 0.6.0 in 42af78105e4cc145ee00dac18a9aba866461c340
