### ISSUE TITLE
tuple_element is declared as a struct but in the standard library headers it's a class

### ISSUE THREAD

**Issue by vlovich** [martinmoene/span-lite#50]
This results in a compilation warning. https://en.cppreference.com/w/cpp/utility/tuple/tuple_element lists it as a class too. Needs to be changed to class + the forward-declaration in non-C++11 mode.

**Comment by martinmoene** [comment]
C++14 and C++20 drafts show this:

```
// 23.4.4, tuple-like access to pair
template<size_t I, class T> class tuple_element;
template<size_t I, class T1, class T2> struct tuple_element<I, pair<T1, T2>>;
```

Is it allowed for a template specialization to be `struct` whereas the base template is `class`, or would that be an editorial mistake?

**Comment by vlovich** [comment]
Same problem appears for tuple_size btw but this does appear to vary by toolchain. libstdc++ & MSVC use struct, libc++ uses class. Unless you want to support arbitrary versions, I think `#pragma GCC system_header` and `#pragma clang system_header` directives might be useful to aid integration rather than trying to match class/struct.

**Comment by vlovich** [comment]
Am I correctly reading the build status page that you only test with different versions of MSVC? Perhaps adding clang & GCC as additional targets (& adding -Wall) might help surface some of these integration issues?

**Comment by martinmoene** [comment]
As far as i can see, only clang produces this warning and "[AFAICS, this warning is wrong and the clang developers should remove it.](https://lists.gnu.org/archive/html/lmi/2016-05/msg00075.html)"

So I'm inclined to add `-Wno-mismatched-tags` to the build.

**Comment by martinmoene** [comment]
@vlovich Can I close this issue?

**Comment by vlovich** [comment]
Yup
