### ISSUE TITLE
Support for iterator constructors/deduction guides

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [martinmoene/span-lite#61]
Is any support for this planned? See [here](https://eel.is/c++draft/span.cons#7) and [here](https://eel.is/c++draft/span.deduct#1) for reference.

**Comment by martinmoene** [comment]
@Ryan-rsm-McKenzie Thanks for your question/suggestion. I wasn't aware yet of these deduction guides. I'll take a look, will not be immediately though.

**Comment by martinmoene** [comment]
span iterator deduction guide:

```Cpp
template<class It, class EndOrSize>
span(It, EndOrSize) -> span<remove_reference_t<iter_reference_t<It>>>;
```
Constraints: It satisfies [contiguous_­iterator](https://eel.is/c++draft/iterator.concept.contiguous#concept:contiguous_iterator).
[std::iter_reference_t](https://en.cppreference.com/w/cpp/iterator/iter_t) (C++20)
[std::remove_reference_t](https://en.cppreference.com/w/cpp/types/remove_reference) (C++14/C++11)

**Comment by Ryan-rsm-McKenzie** [comment]
The new deduction guides are failing to deduce reference types for iterators, presumably because of this line:
https://github.com/martinmoene/span-lite/blob/81f7b15ea0a806718bd2ac72db5f09915d7e4843/include/nonstd/span.hpp#L665

Here's a [godbolt link](https://godbolt.org/z/9v1vco).

**Comment by martinmoene** [comment]
Thanks @Ryan-rsm-McKenzie for your feedback. Currently my attention is a bit too scattered to do a good job in one go. A little back and forth may help :)

Having a look at it...

**Comment by martinmoene** [comment]
@Ryan-rsm-McKenzie I think this issue can be closed, otherwise please reopen it.

**Comment by Ryan-rsm-McKenzie** [comment]
You're missing an iterator based constructor, so code [like this](https://godbolt.org/z/bdbnWa) won't compile.

**Comment by Ryan-rsm-McKenzie** [comment]
I can't re-open the issue because you closed it

**Comment by Ryan-rsm-McKenzie** [comment]
this works

**Comment by martinmoene** [comment]
Thanks @Ryan-rsm-McKenzie !
