### ISSUE TITLE
Some constructors not working with move only types

### ISSUE THREAD

**Issue by im95able** [martinmoene/span-lite#68]
Since restrictions to constructors have been added, some constructors don't work. For example:

```
std::array<std::unique_ptr<int>, 5> a;
nonstd::span s{a.begin(), 5};
```
Was this intended ?

**Comment by im95able** [comment]
Thanks for the quick fix. Could we have a new release ?

**Comment by martinmoene** [comment]
I'll make a new release, perhaps this evening or tomorrow.

**Comment by martinmoene** [comment]
Closing this now, feel free to reopen if needed.
