### ISSUE TITLE
Constructor from iterators is not properly constrained

### ISSUE THREAD

**Issue by krsch** [martinmoene/span-lite#69]
Example: https://godbolt.org/z/9MTYWPYqG
Fails with span-lite, works with std::span (e.g. by enabling `-std=c++20`)
The problem is that `int&` is convertible_to `float const&`. This is not true for `int*` and `float const*` so I think pointers can be used in `span_REQUIRES_T` on line 956, but I'm not sure if this solution has no other bugs.

**Comment by martinmoene** [comment]
Thanks!
