### ISSUE TITLE
operator[] not constexpr with contract checking on

### ISSUE THREAD

**Issue by CrustyAuklet** [martinmoene/span-lite#71]
I am doing a little work on my constexpr [bitpacking library](https://github.com/CrustyAuklet/bitpacker) and wanted to upgrade `nonstd::span` from 0.7.0 to 0.10.0. In doing so I noticed that `operator[]` is no longer constexpr if contracts are on. If I simply mark `impl::is_positive` as constexpr then all my tests pass. Unlike #70 I don't want to disable bounds checking, I like to leave it on in debug builds to enforce the contracts.

Seems like a trivial change, but i can open a MR if you would like. I have the change in [my fork](https://github.com/CrustyAuklet/span-lite/commit/6ccd2e745078f08b99b1dc245603de3a23fdaf29) and all your tests passed.

**Comment by martinmoene** [comment]
Thanks!
