### ISSUE TITLE
Consider implementing P2447

### ISSUE THREAD

**Issue by Pesa** [martinmoene/span-lite#74]
Please consider implementing [P2447](https://wg21.link/P2447) (`std::span` and the missing constructor), possibly as an opt-in optional feature since it hasn't been accepted into the C++ standard yet. Thanks!

**Comment by martinmoene** [comment]
Thanks for your suggestion, Davide. Will look into it.

**Comment by Pesa** [comment]
@martinmoene thanks!

I'm playing a bit with the new constructor (as of commit 052dad8b613aef2a14517f2899b1b438eb5decc7) and I'm getting a strange error with GCC 11.2 (`-std=c++14`)

```
.../detail/nonstd/span-lite.hpp: In instantiation of ‘constexpr nonstd::span_lite::span<T, Extent>::span(std::initializer_list<typename std::remove_cv<_Functor>::type>) [with long unsigned int U = 18446744073709551615; typename std::enable_if<(U == nonstd::span_lite::dynamic_extent), int>::type <anonymous> = 0; T = const unsigned char; long unsigned int Extent = 18446744073709551615; typename std::remove_cv<_Functor>::type = unsigned char]’:
.../detail/nonstd/span-lite.hpp:1088:26: error: initializing ‘nonstd::span_lite::span<const unsigned char>::data_’ from ‘std::initializer_list<unsigned char>::begin’ does not extend the lifetime of the underlying array [-Werror=init-list-lifetime]
 1088 |         : data_( il.begin() )
      |                  ~~~~~~~~^~
```

My code looks like this:

```c++
const Foo& getFoo()
{
  static const Foo foo({'b', 'a', 'r'});
  return foo;
}
```

And class `Foo` has a constructor that takes a `span<const uint8_t>` and makes a copy of its content.

Curiously, `make_span` doesn't trigger the error (but I have to specify the type):

```c++
const Foo& getFoo()
{
  static const Foo foo(make_span<uint8_t>({'b', 'a', 'r'}));
  return foo;
}
```

**Comment by martinmoene** [comment]
Thanks, my quick look is not yet enough to solve this :)

**Comment by martinmoene** [comment]
Here's the [example in Compiler Explorer](https://godbolt.org/z/1nje9Wx5a).

Clang does not issue the warning _'...’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]_.

I'm getting the impression that GCC is trying to be a bit too helpful here.

Do you think suppressing this warning in the relevant location would be a reasonable thing to do?

**Comment by Pesa** [comment]
> I'm getting the impression that GCC is trying to be a bit too helpful here.

Indeed, it's definitely a false positive (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102482)

> Do you think suppressing this warning in the relevant location would be a reasonable thing to do?

Yeah, either suppress the warning (also suggested in [comment 5](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102482#c5) of the GCC bug) or move the assignment into the body of the constructor (suggested in [comment 4](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102482#c4))

**Comment by martinmoene** [comment]
@Pesa Thanks for your very specific help!

**Comment by Pesa** [comment]
Thank you for quickly implementing this extension!

I'm testing commit d9a35a7ff0042049e47d535af7108045baae0be0 and it seems to work as expected. The only small problem is that the `#pragma` throws a warning on GCC 8 and older.

```
.../nonstd/span-lite.hpp:1073:33: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 # pragma GCC diagnostic ignored "-Winit-list-lifetime"
                                 ^~~~~~~~~~~~~~~~~~~~~~
.../nonstd/span-lite.hpp:1092:33: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 # pragma GCC diagnostic ignored "-Winit-list-lifetime"
                                 ^~~~~~~~~~~~~~~~~~~~~~
```

According to https://gcc.gnu.org/gcc-9/changes.html, the warning was introduced in GCC 9.

**Comment by martinmoene** [comment]
You're welcome.

I'll try and guard the `#pragma` :)

**Comment by Pesa** [comment]
Thanks. The latest commit works flawlessly. Tested with GCC 7 through 11, clang 5 through 12 (on Linux with libstdc++), and various versions of Xcode (11.3+).

**Comment by Pesa** [comment]
FYI the `#pragma` workaround for the spurious warning does not work when precompiled headers are used.

**Comment by martinmoene** [comment]
Thanks, it's a pity :)

"GCC #pragma does not work with precompiled header":

- [Bug 64117](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64117) - warning control #pragmas in precompiled headers are not obeyed for template code
- [Bug 56549](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56549) - #pragma once ineffective with BOM in include file

**Comment by Pesa** [comment]
How about implementing the other workaround (move the assignment into the body of the constructor) instead of the `#pragma`?

**Comment by martinmoene** [comment]
Thanks, will look at that.

**Comment by martinmoene** [comment]
Looks like that will require `span_constexpr` (C++11) to become `span_constexpr14`:

```cpp
    template< extent_t U = Extent
        span_REQUIRES_T((
            U != dynamic_extent
        ))
    >
#if span_COMPILER_GNUC_VERSION >= 900   // prevent GCC's "-Winit-list-lifetime"
    span_constexpr14 explicit span( std::initializer_list<value_type> il ) span_noexcept
    {
        data_ = il.begin();
        size_ = il.size();
    }
#else
    span_constexpr explicit span( std::initializer_list<value_type> il ) span_noexcept
        : data_( il.begin() )
        , size_( il.size()  )
    {}
#endif
```

Would this be a sane approach?

**Comment by Pesa** [comment]
hmm true. I'm using C++14 so I didn't notice the constexpr problem. The above approach looks totally sensible to me, though I can also patch my local copy of span-lite (I would understand if you didn't want to "downgrade" the constexpr-ness to support PCHs).

**Comment by martinmoene** [comment]
I've no problem to implement above.

Might someone complain, next step is to make the solution configurable.

**Comment by Pesa** [comment]
Thanks! commit 8f7935ff4e502ee023990d356d6578b8293eda74 works nicely!
I suppose this issue can be closed now.
